name: biobb_MDsetupAPI_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - nb_conda_kernels
  - jupyter_client==7.3.2
  - tornado==6.1
  - jupyter_contrib_nbextensions
  - plotly
  - nglview
  - simpletraj
  - conda